[package]
name = "VulneraX"
version = "0.1.0"
authors = ["Aenosh Rajora <rajora.aenosh.0x01@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
isahc = "0.9.3"
regex = "1.3.9"
rayon = "1.3.0"
chrono = "0.4.11"